
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.


# shared:
#   api_key: a1B2c3D4e5F6


development:
  secret_key_base: ef19612a84153b8157ea31b9f3f3259687785f62d180c4ac5435a3d9c2a4164255381e27f13d6fff6b1ab85655c5f154b5a2a94e72937d1369e9eb381af7bfb2

test:
  secret_key_base: a27e2275934de55d096c509d4cdd2a57c5de7f35aa3c44bd8b786a98f228210f897fffc8863274da54526683a7957221113fc25c54244859bd8626be4be02767

# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
